name: gannar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  meta: ^1.11.0
  shared_preferences: ^2.2.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
